---
- name: Ensure that solr home exists
  file:
    dest: "{{ solr_home }}/data"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
    mode: 0755

- name: Copy default file
  template:
    src: solr.in.sh
    dest: "{{ solr_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart solr

- name: Copy systemd unit
  template:
    src: solr-systemd-unit.j2
    dest: "/etc/systemd/system/{{ solr_service_name }}.service"
    owner: root
    group: root
    mode: 0644
  notify: reload systemd

- name: Check if solr is configured
  stat:
    path: "{{ solr_home }}/{{ item }}"
  loop:
    - solr.xml
    - zoo.cfg
  register: solr_configured

- name: Configure solr_home files if required
  copy:
    src: "{{ solr_install_dir }}/server/solr/{{ item.item }}"
    dest: "{{ solr_home }}/{{ item.item }}"
    remote_src: true
  when: not item.stat.exists
  loop: "{{ solr_configured.results }}"
  notify: restart solr

- name: Check if log4j is configured
  stat:
    path: "{{ solr_home }}/log4j2.xml"
  register: log4j_configured

- name: Configure log4j if required
  copy:
    src: "{{ solr_install_dir }}/server/resources/log4j2.xml"
    dest: "{{ solr_home }}/"
    remote_src: true
  when: not log4j_configured.stat.exists
  notify: restart solr

- name: Ensure that solr user owns the solr folder
  file:
    path: "{{ solr_install_dir }}"
    state: directory
    recurse: true
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"

- name: Ensure solr is running
  service:
    name: "{{ solr_service_name }}"
    state: started
    enabled: true
