---
- name: Cores | Copy our default drupal8 config
  copy:
    src: drupal8-core/
    dest: /tmp/core-config/

- name: Cores | Check current list of Solr cores.
  uri:
    url: "http://{{ solr_connect_host }}:{{ solr_port }}/solr/admin/cores"
    return_content: true
    url_username: "{{ solr_auth|ternary(solr_admin_user, omit) }}"
    url_password: "{{ solr_auth|ternary(solr_admin_pass, omit) }}"
  register: solr_cores_current
  until: solr_cores_current.status == 200
  retries: 5
  delay: 5
  check_mode: false

- name: Cores | Create core directory if required
  file:
    path: "{{ solr_home }}/data/{{ item.name }}/conf"
    state: directory
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
    recurse: true
  when: item.name not in solr_cores_current.content
  loop: "{{ solr_cores }}"

- name: Cores | Copy configuration if required
  command: "cp -r {{ solr_install_dir }}/example/files/conf/ {{ solr_home }}/data/{{ item.name }}/"
  become: true
  become_user: "{{ solr_user }}"
  when: item.name not in solr_cores_current.content
  loop: "{{ solr_cores }}"
  notify: restart solr

- name: Cores | Create cores
  command:
    argv:
      - "{{ solr_install_dir }}/bin/solr"
      - "create"
      - "-c"
      - "{{ item.name }}"
      - "-p"
      - "{{ solr_port }}"
      - "-d"
      - "{{ item.src|default('/tmp/core-config') }}"
  become: true
  become_user: "{{ solr_user }}"
  when: item.name not in solr_cores_current.content
  loop: "{{ solr_cores }}"
  notify: restart solr
