---
- name: Prepare for installation
  import_tasks: prepare.yml

- name: (re)install
  include_tasks: install.yml
  when: >
    download.changed
    or not solr_installed.stat.exists
    or solr_reinstall

- name: configure solr
  import_tasks: config.yml

- name: configure solr cores
  import_tasks: cores.yml

- name: uninstall
  import_tasks: uninstall.yml
  when: solr_uninstall
