---
- name: Remove existing solr installation if required
  file:
    path: "{{ solr_install_dir }}"
    state: absent
  when: solr_reinstall

- name: Ensure java is installed
  apt:
    name: "{{ solr_openjdk_package }}"
    state: present
  when: solr_install_openjdk

- name: install required packages
  apt:
    name:
      - curl
      - rsync
      - lsof
    state: present

- name: Check if solr is already installed
  stat:
    path: "{{ solr_install_dir }}/bin/solr"
  register: solr_installed

- name: Download Apache Solr
  get_url:
    url: "{{ solr_download_url }}/{{ solr_download_path }}"
    dest: "{{ solr_tar_path }}"
    checksum: "{{ solr_checksum }}"
  register: download
