---
- name: Uninstall | Stop Apache Solr service  # noqa ignore-errors
  service:
    name: "{{ solr_service_name }}"
    state: stopped
  ignore_errors: true

- name: Uninstall | Remove the systemd unit
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/systemd/system/{{ solr_service_name }}.service"
    - "/etc/default/{{ solr_service_name }}.service"

- name: Uninstall | Kill all processes run by Solr user  # noqa ignore-errors
  command: killall -u {{ solr_user }} -w
  changed_when: false
  ignore_errors: true

- name: Uninstall | Delete solr installation folder
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ solr_install_dir }}"
    - "{{ solr_home }}"

- name: Uninstall | Delete the Solr user
  user:
    name: "{{ solr_user }}"
    state: absent
