---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart solr
  service:
    name: "{{ solr_service_name }}"
    state: restarted
    enabled: true

- name: reload solr
  service:
    name: "{{ solr_service_name }}"
    state: reloaded
    enabled: true
