---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart solr
  service:
    name: solr
    state: restarted
    enabled: true

- name: reload solr
  service:
    name: solr
    state: reloaded
    enabled: true
