---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint molecule/default/*.yml
  flake8
platforms:
  - name: solr-debian-10
    image: debian:10
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        solr_java_mem: "-Xms256m -Xmx256m"
        solr_password_salt: UdaR6if8queeb5bahZ5Uuhaiwie7Rook
        solr_cores:
          - name: drupal7
            user: d7
            pass: d7
          - name: drupal8
            user: d8
            pass: d8
verifier:
  name: testinfra
  lint:
    name: flake8
