---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: solr7
lint: |
  set -e
  yamllint .
  ansible-lint molecule/default/*.yml
  flake8
platforms:
  - name: solr7-debian10
    image: debian:10
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        solr_version: "7.7.3"
        # yamllint disable-line rule:line-length
        solr_checksum: "sha512:ca9200c18cc19ab723fd4d10f257e27eb81dc8bc33401ebc4eb99178faf4033a2684f0f8b12ae7b659cfeb0f4c9d9e24aaac518a4e00fd28b69854a359a666ed"
        solr_java_mem: "-Xms256m -Xmx256m"
        solr_cores:
          - name: drupal7
            user: d7
            pass: d7
          - name: drupal8
            user: d8
            pass: d8
verifier:
  name: testinfra
  lint:
    name: flake8
